DROP TABLE IF EXISTS Books;
CREATE TABLE IF NOT EXISTS Books (
	Book_ID SERIAL PRIMARY KEY,
	Title VARCHAR(100),
	Author VARCHAR(100),
	Genre VARCHAR(50),
	Published_year INT,
	Price NUMERIC(10,2),
	Stock INT
);
SELECT * FROM Books;
COPY Books(Book_ID, Title, Author, Genre, Published_year, Price, Stock)
FROM 'C:\Users\mmyna\OneDrive\Desktop\onlinebooksdata\Books.csv'
CSV HEADER;
SELECT * FROM Books;
DROP TABLE IF EXISTS Customers;
CREATE TABLE Customers(
	Customer_id SERIAL PRIMARY KEY,
	Name VARCHAR(100),
	Email VARCHAR(100),
	Phone VARCHAR(50),
	City VARCHAR(50),
	Country VARCHAR(100)
);
SELECT * FROM Customers;
SELECT * FROM Customers;
DROP TABLE IF EXISTS Orders;
CREATE TABLE Orders(
	Order_id SERIAL PRIMARY KEY,
	Customer_id INT REFERENCES Customers(Customer_id),
	Books_id INT REFERENCES BOOKS(Book_ID),
	Order_date DATE,
	Quantity INT,
	Total_amount NUMERIC(10,2)
);
SELECT * FROM Orders;
SELECT * FROM Orders;
--1)RETRIEVE  ALL BOOKS IN FICTION GENRE
SELECT * FROM Books
WHERE Genre='Fiction';
--2)FIND BOOKS PUBLISHED AFTER 1950
SELECT * FROM Books
WHERE Published_year>1950;
--3)LIST ALL CUSTOMERS FROM CANADA
SELECT * FROM Customers
WHERE Country='Canada';
--4) SHOW ORDERS PLACED IN NOVEMBER 2023
SELECT * FROM Orders
WHERE Order_date BETWEEN '2023-11-01' AND '2023-11-30';
--5)RETRIEVE TOTAL STOCK OF BOOKS AVAILABLE
SELECT SUM(Stock) AS Total_stock_available FROM Books;
--6)FIND DETAILS OF MOST EXPENSIVE BOOK
SELECT * FROM BOOKS ORDER BY Price DESC LIMIT 1;  
--7)SHOW ALL CUSTOMERS WHO ORDERED MORE THAN 1 QUANTITY OF BOOK
SELECT * FROM Orders
WHERE Quantity>1;
--8)RETREIVE ALL ORDERS WHERE TOTAL AMOUNT EXCEEDS 520
SELECT * FROM ORDERS
WHERE Total_amount>20;
--9)LIST ALL GENRES AVAILABLE IN BOOK TABLE
SELECT DISTINCT Genre FROM Books;
--10)FIND BOOK WITH LOWEST STOCK
SELECT * FROM Books ORDER BY LIMIT 1;
--11)CALCULATE TOTAL REVENUE GENERATED FROM ALL ORDERS
SELECT SUM(Total_amount) AS REVENUE FROM ORDERS;
--12)RETREIVE TOTAL NUMBER OF BOOKS SOLD FOR EACH GENRE
SELECT B.GENRE, SUM(O.QUANTITY) AS Total_books_sold
FROM ORDERS O
JOIN BOOKS B ON O.BOOKS_ID = B.BOOK_ID
GROUP BY B.GENRE;
--13)FIND AVERAGE PRICE OF BOOKS IN FANTASY GENRE
SELECT AVG(PRICE) AS Average_price
FROM Books
WHERE Genre='Fantasy';
--14)LIST CUSTOMERS WHO PLACED ATLEAST 2 ORDERS
SELECT O.Customer_id, C.Name, COUNT(O.Order_id) AS Order_count
FROM Orders O
JOIN Customers C ON O.Customer_id=C.Customer_id
GROUP BY O.Customer_id, C.Name
HAVING COUNT(Order_id)>=2;
--15)FIND MOST FREQUENTLY ORDERED BOOK
SELECT O.Books_ID, B.Title, COUNT(O.Order_id) AS Order_count
FROM Orders O
JOIN Books B ON O.Books_ID=B.Book_ID
GROUP BY O.Books_ID,B.Title
ORDER BY Order_count DESC LIMIT 1;
--16)SHOW THE TOP 3 MOST EXPENSIVE BOOKS OF GENRE FANTASY
SELECT * FROM Books
WHERE Genre='Fantasy'
ORDER BY Price DESC LIMIT 3;
--17)RETREIVE TOTAL QUANTITY OF BOOKS SOLD BY EACH AUTHOR
SELECT B.Author, SUM(O.Quantity) AS Total_books_sold
FROM Orders O
JOIN Books B ON O.Books_ID=B.Book_ID
GROUP BY B.Author;
--18)LIST CITIES WHERE CUSTOMERS WHO SPENT OVER 30 ARE LOCATED
SELECT DISTINCT C.City, Total_amount
FROM Orders O
JOIN Customers C ON O.Customer_id=C.Customer_id
WHERE O.Total_amount>30;
--19)FIND CUSTOMER WHO SPENT MOST ON ORDERS
SELECT C.Customer_id, C.Name, SUM(O.Total_amount) AS Total_spent
FROM Orders O
JOIN Customers C ON O.Customer_id=C.Customer_id
GROUP BY C.Customer_id, C.Name
ORDER BY Total_spent DESC LIMIT 1;
--20)CALCULATE STOCK REMAINING AFTER FULFILLING ALL ORDERS
SELECT B.Book_ID, B.Title, B.Stock, COALESCE(SUM(O.Quantity),0) AS Order_quantity, B.Stock - COALESCE(SUM(O.Quantity),0) AS Remaining_quantity
FROM Books B
LEFT JOIN Orders O ON B.Book_ID=O.Books_ID
GROUP BY B.Book_ID ORDER BY B.Book_ID;
